[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo_password
proxy_mode = True
xmlrpc_interface = 0.0.0.0
admin_passwd = $pbkdf2-sha512$600000$sBYCQCjF.F.rFSLEWCslRA$mUPlwm/khYcZRBY72zIR4lTG0XcYXxhzE3G3QY3jrjyXBtjAksuMTJnvXtYfMlBH2a.9suaq9j59fDbiEVABrQ

